## -----------------------------------------------------------------------------
## GitLab CI configuration file
##
## @author     Lars Thoms <lars@thoms.io>
## @date       2025-01-20
## -----------------------------------------------------------------------------

---
include:
  - project: dl.min/technik/git-templates
    file:
      - /gitlab-ci/go/all.yml
      - /gitlab-ci/yaml/all.yml

variables:
  NAME: hls-utils
...
