## -----------------------------------------------------------------------------
## GitLab CI configuration file
##
## @author     Lars Thoms <lars@thoms.io>
## @date       2023-05-24
## -----------------------------------------------------------------------------

---
variables:
  NAME: hls-utils
  PACKAGE_BASE_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages"
  PACKAGES_URL: "${PACKAGE_BASE_URL}/generic/${NAME}/${CI_COMMIT_TAG}"

default:
  image: alpine
  tags: [dl.min]

stages:
  - build
  - release

build-go-alpine:
  stage: build
  image: golang:alpine
  extends: .go-cache
  parallel:
    matrix:
      - GOOS: linux
        GOARCH: &ARCH [386, amd64, arm, arm64]
  before_script:
    - apk add --no-cache curl
  script:
    - go build -a -buildmode=exe -trimpath -o "bin/app"
    - >-
      curl -H "JOB-TOKEN: ${CI_JOB_TOKEN}" -T "bin/app"
      "${PACKAGES_URL}/${NAME}_${GOOS}-${GOARCH}-musl"
  rules:
    - if: $CI_COMMIT_TAG

build-go-debian:
  stage: build
  image: golang:bullseye
  extends: .go-cache
  parallel:
    matrix:
      - GOOS: darwin
        GOARCH: [amd64, arm64]
      - GOOS: freebsd
        GOARCH: &ARCH [386, amd64, arm, arm64]
      - GOOS: linux
        GOARCH: *ARCH
  script:
    - go build -a -buildmode=exe -trimpath -o "bin/app"
    - >-
      curl -H "JOB-TOKEN: ${CI_JOB_TOKEN}" -T "bin/app"
      "${PACKAGES_URL}/${NAME}_${GOOS}-${GOARCH}"
  rules:
    - if: $CI_COMMIT_TAG

create-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  extends: .release-metadata
  script:
    - echo "releasing version ${CI_COMMIT_TAG}"
  release:
    name: "Version ${CI_COMMIT_TAG}"
    tag_name: "${CI_COMMIT_TAG}"
    description: release-description.txt
    ref: "${CI_COMMIT_SHA}"
  rules:
    - if: $CI_COMMIT_TAG

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - go mod download
  cache:
    paths:
      - .go/pkg/mod/

.release-metadata:
  before_script:
    - apk add --no-cache git
    - >-
      git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty="format:%s"
      | sort -u
      | sed -e 's/^/- /'
      > release-description.txt
...
