## -----------------------------------------------------------------------------
## HLS Utils configuration file
##
## @author     Lars Thoms <lars@thoms.io>
## @date       2023-05-24
## -----------------------------------------------------------------------------

---
# Level of logging:
# - 0 (DEBUG)
# - 1 (INFO)
# - 2 (WARN)
# - 3 (FATAL)
loglevel: 0

server:
  # Bind server to an ip address
  listen: 127.0.0.1

  # Listen to specific port
  port: 8081

# List of streaming endpoints and their API key
streams:
  test: 643c0763-c6f0-4cf6-8f7e-fb2addbd0aee

notify:

stats:
  # Path to `.m3u8` and `.json` files
  data: ./

  # Path to access log
  log: ./hls.log

  # Parse access log (`name` and `sequence` are required)
  regex: "/(?P<name>[a-z0-9-_]+)_(?:src|[0-9]+p)/(?P<sequence>[0-9]+)\\.ts$"
...
